from models.decision import Decision

def rank_and_select(evaluated_strategies: dict) -> Decision:
    # Right now, evaluate_strategies returns the top choice directly based on priority
    # (Affordable now > Affordable with plan > Wait > Not affordable)
    return Decision(
        request_id="", # filled by caller
        amount_safe_to_pay=evaluated_strategies['amount_safe_to_pay'],
        affordability_status=evaluated_strategies['affordability_status'],
        recommended_payment_method=evaluated_strategies['recommended_payment_method'],
        payment_plan=evaluated_strategies['payment_plan'],
        earliest_date_for_full_payment=evaluated_strategies['earliest_date_for_full_payment'],
        spending_changes_needed=evaluated_strategies['spending_changes_needed'],
        decision_explanation=evaluated_strategies.get('decision_explanation', 'Generated by deterministic engine.')
    )
